# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bfb0492b4922fac7add4e07f4f59386730e2f7f20a4e4b6e5d327a2c39a9824b9e712e2804e380e9b6be2d099d27764bf5f4bc3dce9ebfd42572e6b8d23e24

test:
  secret_key_base: 407de66ff77309e73bbe6ca6660014490ff9840023cc432c4d081b3b3e8a3ea05656764fdc8a7782375f9cd1a9b580d6507424180f687ae1a397e89b8fb66b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
